### ISSUE TITLE
What's the state of OCaml Vulkan support?

### ISSUE THREAD

**Issue by anosovic** [OCamlverse/ocamlverse.github.io#103]
[Vulkan](https://www.khronos.org/vulkan/) is a graphics API [set to compete with OpenGL in the coming future](https://en.wikipedia.org/wiki/Vulkan_(API)#Features). the Graphics tab under the Ecosystem heading doesnt mention it at all. how is progress in this area? (for instance, [this project](https://github.com/Octachron/olivine)).

> Vulkan is intended to provide a variety of advantages over other APIs as well as its predecessor, OpenGL. Vulkan offers lower overhead, more direct control over the GPU, and lower CPU usage.

a low-level graphics API plus OCamls HPC would be killer

**Comment by bluddy** [comment]
Cool! AFAIK these are the first bindings for Vulkan. Looks like this code hasn't been released yet, but once it's released, it should definitely be added to Graphics.

**Comment by bluddy** [comment]
I'm closing this because it's currently not actionable. The right forum for this is probably discuss.ocaml.org.
