### ISSUE TITLE
consider encouraging tutorials to be hosted within library source code

### ISSUE THREAD

**Issue by kanishka-work** [OCamlverse/ocamlverse.github.io#104]
The existence of a tutorial is better than no tutorial, even if it's a little out of date.... We might be able to prevent a tutorial from getting out of date by having ocamlverse link out to tutorials, that are hosted as ocaml applications that reside under "tutorials" directory of the library being used, with inline comments providing the narrative. Then the library author can help ensure it is maintained by checking that it compiles with each CI build. The library author can also decide to not accept a tutorial PR if they don't feel they will have the ability to keep maintaining the tutorial.

**Comment by bluddy** [comment]
In theory this is true, I'm just not sure how well this will work in practice. It's already hard enough to get people to post the docs for their library. I'm sure if the tools existed to do a self-checking tutorial properly, it would be doable, and we could then encourage them to use that tool, but I think we're currently missing the tooling. So this is more of an 'ocaml tooling' issue than an ocamlverse issue. It might be useful to open this discussion on discuss.ocaml.org.
