### ISSUE TITLE
Optimization and Iterators

### ISSUE THREAD

**Issue by giltho** [OCamlverse/ocamlverse.github.io#112]
Hi ! 

It seems that this article about iterators gives wrong information : https://ocamlverse.github.io/content/iterators.html

In particular :

>The classic example is something like
>
>```ocaml
>let l1 = [1; 2; 3]
>  |> List.map (fun x -> x + 1)
>  |> List.map (fun x -> x * 3)
>```
>In this example, each stage of the computation needs to be materialized, causing allocation. Instead, we can do
>
>```ocaml
>let l1 = List.to_seq [1; 2; 3]
>  |> Seq.map (fun x -> x + 1)
>  |> Seq.map (fun x -> x * 3)
>  |> List.of_seq
>```
>This version will not allocate the intermediate steps.

Not only is it allocating intermediate steps, but it also seems to be using 3 to 4 times the memory 😅 
See discussion here : https://discuss.ocaml.org/t/seq-vs-list-optimization/6885/15

I wanted to open a PR, but I don't know what should be written there instead. 
Libraries like `Iter` also warn in the documentation that `Iter.to_list`  consumes 2*n memory...

**Comment by bluddy** [comment]
Thanks! You're absolutely right.

I think I'd want to change the explanation about the Seq version to go into more detail: the intermediate steps will be allocated one element at a time, but will not take up the full memory needed by a list at once (the minor/major heap thing derives from this property, and we don't need to go into detail about that here).

Then, I think we need the Iter version, which will not allocate any memory outside of the original list.

Feel free to suggest a PR.

**Comment by bluddy** [comment]
I went ahead and modified the article. Feel free to offer improvements.
Closed by 6316d3da6410a653c56a3ecff3c8bc077c86a3a1
