### ISSUE TITLE
Outdated information in the "Future of OCaml" page

### ISSUE THREAD

**Issue by ColourGrey** [OCamlverse/ocamlverse.github.io#121]
A Google search for "future of ocaml" led me to the ["Future of OCaml" page on OCamlverse](https://ocamlverse.github.io/content/future_ocaml.html). While I know nothing about the development of OCaml, it seems that much of the information therein is outdated. For instance:

- the "best fit" allocator seems to [have already been implemented](https://github.com/ocaml/ocaml/pull/8809#issuecomment-542231988), so it's not in the future anymore;
- what was then presented as [the development branch of Flambda 2.0](https://github.com/mshinwell/ocaml/tree/flambda2.0) has received that last commit in November 2019;
- work in typed algebraic effects was said to be going on at https://github.com/lpw25/ocaml-typed-effects; a quick look at that repository shows the last change performed to be from June 2018.

I believe that somebody knowledgeable in the status of OCaml development should filter the information on that page, remove what has become outdated and add the true future development directions.

**Comment by pmetzger** [comment]
Algebraic effects are still being quite actively worked on, as is flambda 2. I'm not sure *where* they're being worked on.

**Comment by omasanori** [comment]
Now OCaml 5.0 had been released and 5.1 is approaching by the way...

* Flambda 2: https://github.com/ocaml-flambda/flambda-backend along with the Cfg backend (I have no idea on the Cfg backend, though...)
* Algebraic effects: some has landed in 5.0, leaving https://github.com/ocaml/ocaml/pull/12309
* *Modes* (introduction articles [part 1](https://blog.janestreet.com/oxidizing-ocaml-locality/) and [part 2](https://blog.janestreet.com/oxidizing-ocaml-ownership/)) being implemented in the [Jane Street's development tree](https://github.com/ocaml-flambda/ocaml-jst) may be good candidate for new topic on the page.
