### ISSUE TITLE
A Link rot of OWL proposed project page on Help Wanted page

### ISSUE THREAD

**Issue by kirisky** [OCamlverse/ocamlverse.github.io#137]
Hi!

Just found a link rot ([OWL proposed project page](https://ocaml.xyz/project/proposal.html)) on the [Help Wanted](https://ocamlverse.github.io/content/help_wanted.html) page.

I checked the OWL [website's repo](https://github.com/owlbarn/owlbarn.github.io), seems they've deleted that page. 

Can I delete the link on the page?

**Comment by bluddy** [comment]
sure! go for it.
