### ISSUE TITLE
Adding a dedicated domain

### ISSUE THREAD

**Issue by bbatsov** [OCamlverse/ocamlverse.github.io#150]
I think it'd be nice if the site adopted a dedicated domain like `ocamlverse.net/org/whatever`. Domains are dirt-cheap (usually around $10/year) and this helps with the discovery/remembering and makes the site hosting-agnostic. If you want I can even buy the domain and just send you the necessary config for GitHub Pages to use it.

**Comment by bluddy** [comment]
That's a good idea. Sorry I missed this. I don't mind buying the domain, but I don't know how to configure it for github pages, so I'd be happy if you directed me to it.

**Comment by bbatsov** [comment]
@bluddy It's a pretty simple process that's documented here https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/about-custom-domains-and-github-pages

**Comment by bluddy** [comment]
Any thoughts about which domain to get? .org? .net? .xyz?

**Comment by bbatsov** [comment]
I'd get `.net` or `.org`. Personally I prefer `.net`.

**Comment by bluddy** [comment]
Do you have any idea if SSL comes free with the domain (via github), or if there's an extra service required?

**Comment by Et7f3** [comment]
Let's encrypt provide TLS certificates for free and is supported by most host provider.

**Comment by bbatsov** [comment]
GitHub can handle this automatically. I've used their certificates for all my sites hosted on GitHub Pages.

**Comment by bluddy** [comment]
Closed after switching to `ocamlverse.net`.
