### ISSUE TITLE
Make github pages version nicer?

### ISSUE THREAD

**Issue by bluddy** [OCamlverse/ocamlverse.github.io#2]
It would be nice if the github pages version of the site had a sidebar and such niceties. Maybe a nicer theme.

EDIT: See https://github.com/mmistakes/minimal-mistakes/issues/476

**Comment by bluddy** [comment]
Keep in mind that we've already imported the default.html in _layouts for the slate theme, so switching themes must be done cautiously.

**Comment by pmetzger** [comment]
Stupid question, what's the URL for the github pages version?

**Comment by bluddy** [comment]
https://bluddy.github.io/ocamlverse or just https://git.io/overse

**Comment by bluddy** [comment]
We might want to take some inspiration from https://reasonml.github.io/. We don't need anything near as fancy, but taking elements of it would be nice.

**Comment by bluddy** [comment]
This Jekyll theme seems to have sidebar support, plus it looks pretty great: https://github.com/mmistakes/minimal-mistakes/issues/476

**Comment by bluddy** [comment]
Linking this page so we have it for reference: https://help.github.com/articles/adding-a-jekyll-theme-to-your-github-pages-site/

**Comment by bluddy** [comment]
I looked into other themes last night. I looked at minimal-mistakes, [lanyon](http://lanyon.getpoole.com/), and [documentation-theme](http://idratherbewriting.com/documentation-theme-jekyll/). Of these, lanyon is my favorite so far, but I can easily be convinced to choose documentation-theme if we want to modify it a little. Minimal-mistakes so far seems heavily biased towards blog posts. It has a ton of features, but I couldn't get it to do what I wanted. Had I been able to tame it, it may have become my favorite. So no conclusions so far.

I'm reading up on the jekyll docs. I'm currently missing some pieces about how this stuff works.

Also, I'll be offline until Monday night, so if anyone else wants to dig in, feel free to do so.

**Comment by anuragsoni** [comment]
@bluddy I'll start by saying thanks for starting this initiative!

Sidebars and search are some features that would indeed be very nice to have. I like the layout of the reasonml/bucklescript websites. They seem to use [Docusaurus](https://github.com/facebook/Docusaurus) for the website. Could that work for the type of content in ocamlverse?

**Comment by bluddy** [comment]
Github pages uses jekyll as its default generation engine, and it seems like docusaurus is now a new alternative from facebook using node.js. It takes a little more work to integrate it with github pages, so for now I think it makes sense to try stick with jekyll (though I could be convinced otherwise). For Reason folks, node.js is a natural fit. Also, I think docusaurus makes more assumptions about site layout and features that don't necessarily correspond to ocamlverse's design.

Both these platforms are doing really simple things, so I think we can ultimately manage with either one, and the closer integration with github pages makes this a little easier for us. At least that's my point of view right now.

**Comment by anuragsoni** [comment]
Sounds fair. I agree that the ease of integration with github pages does make Jekyll a more attractive option to start with

**Comment by bluddy** [comment]
After investigating some themes and learning about jekyll, I actually think it'll be easier to just edit our own css to make it nicer. @pmetzger let me know if you're interested.

I recommend setting up jekyll locally following [these instructions](https://help.github.com/articles/setting-up-your-github-pages-site-locally-with-jekyll/) so you can try stuff out.

The easiest way to modify css is to follow the instructions [here](https://help.github.com/articles/customizing-css-and-html-in-your-jekyll-theme/). I'm personally working on getting a sidebar going.

**Comment by anuragsoni** [comment]
Jekyll's primary goal seems to be to support creation of blogs. I'm not sure how much effort /maintenance it will take to mold it to support a proper documentation/wiki style layout while keeping the structure easy to understand. Is native support by github the only reason to stick with it? There might be other tools that better support the style of layout that suits ocamlverse better.

Personally I like the style provided by [Sphinx](http://alabaster.readthedocs.io/en/latest/index.html) when it comes to reading technical content, or a documentation/wiki style heavy content.

**Comment by bluddy** [comment]
Sphinx uses restructuredText, which while not bad, is going to be a new syntax for contributors to learn. On the other hand, everyone knows markdown.

All of these tools ultimately do very simple things, and I'm not sure we need to switch from Jekyll right now. At the end of the day, it's just generating static pages. The convenience of having it built into github pages is quite significant.

**Comment by anuragsoni** [comment]
Sphinx now supports [markdown](http://www.sphinx-doc.org/en/master/usage/markdown.html)

I agree that there is nothing that complicated in all of these tools, but It might just be more difficult to switch layouts once we have a substantially more amount of content.

That being I was merely stating my preference for a documentation layout, which is highly subjective 😄 At the end of the day the important part if working towards a good resource for people interested in OCaml and i'll be happy to support any effort towards that.

**Comment by bluddy** [comment]
> Sphinx now supports markdown
Oh, interesting.

Well, listen, I'm open to anything that keeps our light process while improving the results. I really like that I can navigate OCamlverse equally well from the github view, starting with the readme. I really like that we can be concerned with content first. If you think you can come up with a process that's light, that automatically updates the site, and that looks better and has a sidebar + search or something like that, you can fork and create that in a branch and I'll check it out. I can't promise we'll switch to it, but if it has these properties, I may be tempted to do so.

Of course you're right about the subjective aspects -- I can't guarantee the other admins won't critique the new look, but presumably that can be modified on any platform.

**Comment by bluddy** [comment]
I think I'm pretty happy with the look of the site right now (aside from access from mobile, which has its own issue). We can improve on it if need be, but for I'm good with where it's at. Closing.

**Comment by mjstenbe** [comment]
Any progress with sidebar support in GitHub pages?

**Comment by kanishka-work** [comment]
(Side note, I recently did a scan of site generators and see some potential in (vercel | netlify) + (hugo | 11ty), if at some point a jekyll alternative is being considered. I agree with trying to use github pages by default)
