### ISSUE TITLE
Migrate to the OCamlverse organization

### ISSUE THREAD

**Issue by bluddy** [OCamlverse/ocamlverse.github.io#24]
It turns out that with github's admin rules, I cannot give anyone else real admin access. That's unacceptable, and looking into the problem, I found out our only solution is to create a github organization.

I created the ocamlverse organization for this purpose. You might think we should try get under the ocaml organization, but a) we don't run that and b) we can't possibly make everyone members of that organization, and our policy is explicitly that everyone can get write access by default. So this is what makes the most sense (I think).

Unfortunately, I can't do much more than creating the org right now. I don't have outside ssh access at work, so I can't clone and create an ocamlverse repo. We don't want to fork -- that creates a 'forked from' link that remains unless we get github to help us.

I'll work some more on this tonight. If one of the original 'admins' wants to help with this, let me know here and I'll give you admin access in the new org. **EDIT**: scratch the following, it's actually really easy to migrate. (In any case, migrating earlier rather than later makes sense -- there are many things that will need to be replicated like issues and labels, and the longer we wait, the harder it'll be.)

**Comment by bluddy** [comment]
In the meantime, let's continue as usual. Don't let this detract you from contributing whatever you want to contribute.

**Comment by kalouantonis** [comment]
@bluddy Looks like this is done now right? Can we close the issue?

**Comment by bluddy** [comment]
@kalouantonis I'm hoping to get a response from github about changing the git.io/overse redirect. But honestly, ocamlverse.github.io is really natural, so I'll close the issue.
