### ISSUE TITLE
Add new user quick setup templates/instructions

### ISSUE THREAD

**Issue by mars0i** [OCamlverse/ocamlverse.github.io#27]
1. It's worth having a page or two with specific instructions about how to start an OCaml project.  It will specify a project configuration including a combination of choices that work together and that are among those configurations that are common.  That way, if for example you don't want to understand `Dune` configuration, and just want to build some code and see how it works, you can.  

e.g.:
> Create a "src" directory and put a jbuild file there that contains ....  Put your first source file foo.ml there.  (If you want a .mli file, see such and such page.  If you don't know whether you want one, it can wait until you now why you want it.)

That's probably not the best format, but I wanted to convey the idea.

There should be links to explanations of the choices, or brief explanations on the template page, if it's not too much of distraction.  ("Create a src directory, or use the name of your choice, as long as it's not "_build".  Dune will find the jbuild files anywhere under your project directory.)  The idea is to provide a path to a working setup for those who don't want to understand all of the details yet, but make information available for those that do want to understand what they're doing.  

2. It might turn out that it's worth having two or three variants for different quick setups. 
> ... For a traditional OCaml setup, do this.  If you are reading *Real World OCaml* and want to work with `Base`/`Core_kernel`/`Core` do this.  If you want an extended library with good API docs and aren't reading RWO, do blah blah.  If you want to do web programming with `js_of_ocaml`, do that.  If you want to do web programming with `bucklescript`, go to this page and use one of the `bsb` template scripts there.  Etc.

All of this is just meant to be a suggestive starting point for thinking about what to include and how to write it and format it.  (And I truly mean no insult to `Core` or JS.  In the long run I expect that `Core` and friends will be much easier for newbies than they are now.  But at present it's worth letting new users know that there's a tradeoff.  No reason to turn off someone who's not reading RWO.  They can get into `Core` later, and they very possibly will at some point.)

3. In the long run, it might be worth creating template-creation scripts that do all of the steps for the user.  However, in that case it would be good to maintain the links to information about what the script is doing.  This should stay in Ocamlverse, rather than being moved to the script itself, so that links are easier to maintain.

4. The main page or pages for these setup instructions should be under `Beginners` under `Learning`.

Question: If there are already good instructions for part of the process in a location that is likely to be maintained, should the quick setup pages simply refer to them?  For example, ocaml.org is always likely to have a "How to install OCaml" page, and a page on installing packages with `opam`.

**Comment by bluddy** [comment]
I would add that quick-start instructions should be linked from the main page (Getting Started With OCaml) or some such thing.

Re: your question, my opinion is that we can maintain these kinds of things pretty well (eventually, at least -- it's ok to link initially). If we come up with good instructions, we can copy that content over to ocaml.org. The strength of low-latency/fast updates is on ocamlverse's side, and we should make use of that to improve the content.

**Comment by mars0i** [comment]
Yes, both points make sense to me.

**Comment by mars0i** [comment]
This information is relevant: http://jbuilder.readthedocs.io/en/latest/project-layout-specification.html?highlight=opam

**Comment by bluddy** [comment]
@bobbypriambodo has great articles on medium we could borrow from for this (with his permission).

**Comment by bluddy** [comment]
The quickstart page is now a reality (and can be expanded upon at will). Closing.
