### ISSUE TITLE
Consider moving to ocaml-community

### ISSUE THREAD

**Issue by rizo** [OCamlverse/ocamlverse.github.io#59]
Now that we have a [community organization](https://github.com/ocaml-community) I think it makes sense to move this project there. It will benefit from more consistent exposure and potentially attract more contributors.

I've also proposed this for [awesome-ocaml](https://github.com/rizo/awesome-ocaml/issues/147).

**Comment by pmetzger** [comment]
@bluddy ?

**Comment by bluddy** [comment]
Two issues I can think of are:
1. ocamlverse currently aims to be a resource anyone can edit, while ocaml-community only includes specific contributors.
2. We won't be able to have the same website name, but rather ocaml-community.github.io/ocamlverse, which is way too long.

**Comment by bluddy** [comment]
Closing for the above reasons.
