### ISSUE TITLE
Dune (the article and dune behaviour)

### ISSUE THREAD

**Issue by RogerTarani** [OCamlverse/ocamlverse.github.io#60]
I report here errors in this article as well as my discovery of dune's behaviour. And open a discussion about dune. I apologize for the EDIT due to confusion (I'm learning dune).

1/ Consistency regarding jbuilder/dune
What about modifying the text of the following command
`$ opam install merlin ocp-indent dune utop`
accordingly to the text that follows: 
> - dune, the installable library of Dune. At the point of this writing, Dune’s latest version is 1.0.1.

In the original article we can see (today):
`$ opam install merlin ocp-indent dune utop`

2/ Is putting .ml files in a /bin directory a practice enforced by dune and recommended for OCaml coding?
> To keep things tidy, let’s move the program to a subdirectory. We will name the directory bin, a convention I use as a place to put entry point modules for executables:

I don't believe main.ml is executable code. Sure that it's can be interpreted, but it looks like source (and dune file is configuration code). 
Is it a convention to put source files in bin/ when using dune?
What about using a more natural and meaningful  src/ directory?

3/ dune exec is doing more that I believed: first it builds then it executes.
The following instructions work:
> $ dune clean
> $ dune exec bin/main.exe
> Hello, world!

But it reveals that  `dune exec` includes `dune build`.
That should certainly be a command like `dune build bin/main.exe ; dune exec bin/main.exe`
While in the (nicely presented) dune documentation we can find the following ambiguous assertion: 
> The executable can **ran** with: $ dune exec ./hello_world.exe 

It doesn't say that it doesn't build but it lets think that it only runs the .exe file.
[https://jbuilder.readthedocs.io/en/latest/quick-start.html#building-a-hello-world-program](https://jbuilder.readthedocs.io/en/latest/quick-start.html#building-a-hello-world-program)

We also can see the same in the Libraries paragraph:
> Now, open up bin/main.ml and replace the contents with the following:

> $ dune exec bin/main.exe
> 5
> 2

It works but we see also that `dune exec ...` does compile AND exec.
Additional test: just add an error somewhere in main.ml (Xopen instead of open) => main.exe is no more executable, so it has been modified.

4/ Librarie, paths, etc.
EDIT : For mental sanity of readers (especially beginners to whom I dedicate this post), why the original author and the Ocamlverse author are using here "lib" for the name of the library declared to dune AND for the name of the directory in which is located all the library stuff?? This is highly confusing when we should learn the language AND the toolings.

So I was first confused by that and believed that 
DELETED : 
(* "we can create a lib library by putting some .ml files in a directory if we declare that "lib" library in the dune file":
```
$ cat lib/dune
(library
  (name lib))
```
So far, I've been using modules for that with nested modules inside. When I handle a .ml module file it has no adherence with the name of the place where I put it!
Is it specific to dune?
For me, this is not enforcing a "first-class modules policy" claimed in RWO or in other places. *)

Here is how it seems to me more simple and consistent to use modules declared to dune (in a lib/dune file) as a library that gathers, then made available for my main.ml program:
" To constitute a dune library with a set of .ml modules, I put them in a directory with a dune file where is declared the library name, then used for compilation and linking. " (this is a basic rule)
> $ cat bin/dune
> (executable
>   (name main)
>   (libraries foo))

> $ cat lib/dune
> (library
>   (name foo))

> $ cat lib/math.ml
let add x y = x + y
let sub x y = x - y

> $ cat lib/math2.ml
> let mul x y = x * y 

Then I can use in my main.ml program the functions offered by the Math and Math2 modules seen as modules nested in what appears as "Foo module" (in main.ml I use Foo.Math and Foo.Math2).
And this "Foo module" is declared to dune as a "Foo library".

> $ cat bin/main.ml
> open Foo.Math
> open Foo.Math2
> let () =
>   let result = add 2 3 in
>   print_endline (string_of_int result);
>   let result = sub 3 1 in
>   print_endline (string_of_int result);
>   let result = mul 2 3 in
>   print_endline (string_of_int result)

At last,  regarding the naming and usage of directories (bin/ and lib/), which is one of my/our questions, I'll do as recommended by the dune team.

In this post, there are suggested corrections for improving the article, as well as key questions regarding dune which is becoming THE  build system for OCaml.
I think that the dune team should (must!) expose clearly the complete and consistent rules that an OCaml coder must respect when using dune.

EDIT (I deleted what resulted from the lib directory/lib library confusion)
In fact I mean that writing dune files by hand is error prone (i tried to write opam files by hand and went into trouble because of package incompatibilities).
Is there a way for us and for dune to define the dependencies of a project with real-time consistency check, instead of letting people stuck with defining ocamlfind "library files" (META), "opam package files" (opam) and dune build files (dune) all over a tree of the file system?
Okay, you can say that I don't get the "whole story" about dune and ocamlfind and opam. Maybe, pls tell me.

And you can say that I should have read all the dune doc. 
You are right (I will!), but the (recurrent) issue is that we find too many articles and event official (dune, OCaml) documentation (see dune Quick start) with incomplete or inconsistent information which result in confusion when trying to learn from it. 
How do you want  beginners to handle that? (fully beginners in coding, or coming from other programming languages).

This is the paradox I see with the Ocaml tooling/ecosystem: type safe "industrial strenght" language, but unsafe or poor documentation for tools.
But this is improving.

**Comment by pmetzger** [comment]
I'm sorry, but I'm not exactly sure what it is that you would like us to do here?

**Comment by pmetzger** [comment]
Just to be clear: this isn't a general OCaml help source, this is the trouble ticket system for the text on the OCamlverse web site.

**Comment by RogerTarani** [comment]
Ok. 
Pls. consider improving the article with 1/, 3/ and 4/ (regarding the name of the lib used to package the Math module: Foo instead of Lib eliminates the ambiguity with lib/ directory).

**Comment by pmetzger** [comment]
I'm not sure I can parse that better. My bad, maybe I'm too tired. Perhaps you could do a pull request?

**Comment by RogerTarani** [comment]
I never made comment about OCamlverse before.
Who is supposed to consider suggested improvements, to validate some of them and to edit the targeted file accordingly?

**Comment by pmetzger** [comment]
Do a github pull request.

**Comment by bobbypriambodo** [comment]
Thanks for the questions. As the original author of the Dune article, I'll try to address them a bit later.

**Comment by bobbypriambodo** [comment]
@RogerTarani 

> 1/ (typo)

Ah, you mean about `$ opam install merlin ocp-indent jbuilder utop`. Yes, it seems I missed updating that. You can open a pull request for this if you want.

> 3/ (dune exec does also a build)

I believe I have noted this exact thing in the article: _Note that since Dune 1.0+beta18, exec command also implies build, so going forward we will mostly only use exec to build and run our program._

> 4/ (regarding the name of the lib used to package the Math module: Foo instead of Lib eliminates the ambiguity with lib/ directory).

I'm not sure if `Foo` is better than `Lib`.  The reason I used `lib` for that part is that, for small projects, we can just dump all our module source in the `lib` directory and they will all be available as modules in `Lib.*`.

The way I see it can be somewhat improved is that we use a `lib/math/` directory, so:

```
$ ls lib/math
dune
math.ml

$ cat lib/math/dune
(library
  (name math))
```

But that seems overly complex for a simple example (raises questions such as, does every `.ml` file needs to be in a separated directory?).

In general, the convention for Dune I think is that the name of the library should match the directory they are contained in. Since we're using `lib` and putting our sources there, the convention will be the library is also named `lib`. Hope that helps.

**Comment by RogerTarani** [comment]
PS : @bobbypriambodo 
Can you pls  tell us how to quickly setup VSCode to get a full OCaml IDE ?
I mean the configuration required after having installed VScode and the vscode-reasonml extension, in order to edit code (auto-completion, display types, code indentation), to evaluate a phrase/region/"buffer" with the OCaml compiler, to launch the debugger, and to build the executable. 
I don't know at all MS tools.
Maybe it's easy, or not!

**Comment by pmetzger** [comment]
As this isn't about problems on the site any longer, I'm going to close it.

**Comment by RogerTarani** [comment]
@anuragsoni I understand that the only thing required to use Merlin is to have a .merlin file at the root of the project tree. AFAIK, Dune now generates the .merlin file(s) and erases .merlin file written by hand.

Concerning VSCode, do you mean that it really works out of the box? 
It looks like we must handle some VSC json configuration files for being able to get an "OCaml evaluation buffer".
When I do Start Without Debugging (Ctrl-F5), I have a Select Environment menu, that proposes:
> Node.js
> More...

If I type Ocaml, I see
```
Ocaml (hackwaly ; deprecated : use vscode-reasonml instead which is already installed!)
OCaml Debugger (hackwaly)
```
Which lets me think there is a simple configuration problem like specifying where is the OCaml compiler.


Concerning Merlin, in my case, I can write .ml files but although there is a .merlin file generated by Dune, the Merlin features are not available:
> X command 'reason.showMerlinFiles' not found
> ! Cannot find merlin binary at "ocamlmerlin". Source: OCaml and Reason IDE (Extension)

I suppose the cause of those two issues is that VSC doesn't know where is the OCaml stuff (OCaml compiler, Merlin, etc.).
I'll open a discussion in case it's a trap, and not a very stupid mistake I made. 


EDIT: I launched VSC from CLI after having cleanly selected a switch and Merlin works now. But the  evaluation of an OCaml expression is not yet possible.

**Comment by pmetzger** [comment]
@RogerTarani The purpose of the issue tracker for ocamlverse is to discuss problems with ocamlverse specifically. There are many resources, including IRC and discord channels, mailing lists, the discuss web site, etc., for asking questions about OCaml. Please use one of them.
