### ISSUE TITLE
dune-workspace: keep the notion and eliminate the dune-workspace file?

### ISSUE THREAD

**Issue by RogerTarani** [OCamlverse/ocamlverse.github.io#61]
I understand the difference between  a dune workspace and a dune project.
**workspace**: the workspace is the subtree starting from the root. It can contain any number of projects that will be built simultaneously by dune
**project**: a project is a source tree, maybe containing one or more packages. 
See [https://jbuilder.readthedocs.io/en/latest/terminology.html](https://jbuilder.readthedocs.io/en/latest/terminology.html)

Suggestion of improvement for the definition of _project_: a project is located in a dune workspace. If there is only one dune project defined with a dune-project file, the workspace is implicitly defined by this dune project.

Suggestion of improvement about dune workspace: wouldn't it be simple and useful to enforce the definition of a workspace with a dune-workspace file? Or much better: simply keep the notion of dune workspace but eliminate the dune-workspace file, so that the root will be flexibly defined by the higher dune-file when projects are modified?

See [https://jbuilder.readthedocs.io/en/latest/usage.html#dune-workspace](https://jbuilder.readthedocs.io/en/latest/usage.html#dune-workspace)

**Comment by pmetzger** [comment]
I'm not sure what it is exactly that you wish for us to do? This is not a general help location for OCaml, this is just the issue tracker for bugs on the OCamlverse web site.

**Comment by RogerTarani** [comment]
From the Dune documentation at [https://jbuilder.readthedocs.io/en/latest/terminology.html](https://jbuilder.readthedocs.io/en/latest/terminology.html), the _Edit on GitHub_ link gets to [https://github.com/OCamlverse/ocamlverse.github.io/blob/master/content/learning.md](https://github.com/OCamlverse/ocamlverse.github.io/blob/master/content/learning.md).
There, Issues is a natural place to provide improvement suggestions for Dune documentation.
Where else am I supposed to to do it?

**Comment by pmetzger** [comment]
> From the Dune documentation at https://jbuilder.readthedocs.io/en/latest/terminology.html, the Edit on GitHub link gets to https://github.com/OCamlverse/ocamlverse.github.io/blob/master/content/learning.md.

I'm afraid when I click on the one I don't get to the other, and frankly I would have been shocked if I had, as the repositories are unconnected. I'd suggest that if you have problems with the Dune documentation, you should talk to the Dune developers. OCamlverse has nothing to do with Dune development.

**Comment by RogerTarani** [comment]
EDIT (after this issue was closed): it seems that the _Edit on Github_ link has been changed in the meantime (it is now in 404). I could also make a mistake.
The Dune issue has been reported to the right place: [https://github.com/ocaml/dune/issues/1349].
Thanks.(https://github.com/ocaml/dune/issues/1349)
