### ISSUE TITLE
fix broken urls in guidelines

### ISSUE THREAD

**Issue by sanette** [OCamlverse/ocamlverse.github.io#76]
page:

https://ocamlverse.github.io/content/documentation_guidelines.html

in this paragraph, both links are broken.

> An example would be Simon Cruanes’ sequence documentation, where the elements are neatly organized into sections, such as “Build a sequence”, “Consume a sequence”, etc. Another example is Daniel Bünzli’s Fmt documentation.

**Comment by bluddy** [comment]
Thanks for noticing! Fixed.
