### ISSUE TITLE
VSCode editor setup links to repo marked as unmaintained

### ISSUE THREAD

**Issue by shonfeder** [OCamlverse/ocamlverse.github.io#84]
I don't use VSCode myself, but noticed that https://github.com/reasonml-editor/vscode-reasonml announces it is unmaintained at the top of the page.  Probably a good idea to either update that link to the maintained plugin, or make a note that the plugin is still preferred, even tho it is not actively maintained.

**Comment by bluddy** [comment]
Would you like to make the change? I'd be happy to merge it.

**Comment by shonfeder** [comment]
I would be happy to make the change, but I don't know which change to make as I'm not a VSCode user. Does anyone with eyes on this use VSCode regularly? If so, which is the preferred package at this point?

If no one this expertise, I may be able to budget time to set up VSCode and trail the existing packages to see how they measure up and what sort of configuration may be needed.

**Comment by bluddy** [comment]
We should probably ask on discord. I don't use it either.

**Comment by shonfeder** [comment]
Cool, I'll see if I can hunt someone down. :+1:
